// lib/constants/meteors.ts
// Static data for major annual meteor showers.
// Used by getNextMeteorShower (pure, no external dependency).

import type { MeteorShower } from "../api/schemas";

export const MAJOR_METEOR_SHOWERS: MeteorShower[] = [
  {
    name: "Quadrantids",
    peakMonth: 1,
    peakDay: 3,
    description: "A sharp, brief burst that rewards precise timing. Fast meteors with persistent trains, but the peak window is only about six hours wide — a single overcast night can mean missing the whole show.",
    activityLevel: "Moderate–High",
    parentComet: "the near-Earth asteroid 2003 EH1, thought to be the rocky remnant of a comet that broke apart centuries ago — making Quadrantids unusual as a shower with an asteroid parent rather than an active comet",
    radiantConstellation: "Boötes (the Herdsman), near the region of the now-defunct constellation Quadrans Muralis — which is where the shower gets its name",
    peakZHR: "up to 60–200 meteors per hour, but only during a narrow six-hour window; catching the true peak requires precise timing",
  },
  {
    name: "Lyrids",
    peakMonth: 4,
    peakDay: 22,
    description: "One of the oldest recorded meteor showers, with observations dating back over 2,600 years. Moderately fast meteors with bright fireballs, and occasional outburst years that dramatically raise rates without warning.",
    activityLevel: "Moderate",
    parentComet: "Comet Thatcher (C/1861 G1), which has an orbital period of roughly 415 years and won't return to the inner solar system until around 2283",
    radiantConstellation: "Lyra (the Harp), near the brilliant star Vega — one of the brightest stars visible from the northern hemisphere",
    peakZHR: "around 15–20 meteors per hour in typical years, with rare outbursts reaching 100 or more",
  },
  {
    name: "Eta Aquariids",
    peakMonth: 5,
    peakDay: 6,
    description: "Some of the fastest meteors of any annual shower, frequently leaving glowing trains that linger for several seconds. The radiant barely clears the horizon before dawn in the northern hemisphere, giving southern latitudes a much better show.",
    activityLevel: "Moderate",
    parentComet: "Halley's comet — the same debris trail that produces the Orionids in October, just a different section of it encountered on the other side of Earth's orbit",
    radiantConstellation: "Aquarius (the Water Bearer), near the star Eta Aquarii, which rises only a couple of hours before dawn at northern latitudes — limiting the viewing window significantly",
    peakZHR: "around 50–85 meteors per hour from the southern hemisphere; northern viewers see rates closer to 20–30",
  },
  {
    name: "Perseids",
    peakMonth: 8,
    peakDay: 12,
    peakEndMonth: 8,
    peakEndDay: 13,
    description: "The most-watched annual shower in the northern hemisphere. Warm summer nights, consistently high rates, and abundant bright meteors and fireballs make this the go-to event. Activity stays elevated for several nights, giving multiple chances to observe.",
    activityLevel: "High",
    parentComet: "Comet Swift–Tuttle (109P/Swift–Tuttle), one of the largest objects known to make repeated close passes of Earth — its nucleus is roughly 26 km across",
    radiantConstellation: "Perseus (the Hero), in the northeastern sky — the radiant climbs higher as the night progresses, with rates improving steadily toward dawn",
    peakZHR: "around 90–100 meteors per hour under ideal conditions, with occasional outburst years reaching 150 or more",
  },
  {
    name: "Orionids",
    peakMonth: 10,
    peakDay: 21,
    description: "Fast, graceful meteors that often leave persistent glowing trains lasting several seconds. This is Earth's second annual encounter with Halley's comet debris — the Eta Aquariids in May being the first. Best viewed in the pre-dawn hours when the radiant is highest.",
    activityLevel: "Moderate",
    parentComet: "Halley's comet — Earth crosses Halley's debris trail twice a year; this is the second encounter, about four months after the Eta Aquariids",
    radiantConstellation: "Orion (the Hunter), near the raised club of Orion in the northeastern sky — the radiant rises well after midnight, so rates improve toward dawn",
    peakZHR: "around 20–25 meteors per hour, with activity spread over several nights near the peak",
  },
  {
    name: "Leonids",
    peakMonth: 11,
    peakDay: 17,
    description: "Famous for producing the most spectacular meteor storms in recorded history — the 1833 storm reportedly produced tens of thousands of meteors per hour. Most years are quiet, but the shower delivers some of the fastest meteors of any annual event.",
    activityLevel: "Moderate–High",
    parentComet: "Comet Tempel–Tuttle (55P/Tempel–Tuttle), which orbits the Sun every 33 years — when Earth passes through a dense filament of its debris shortly after the comet's return, storm-level rates are possible",
    radiantConstellation: "Leo (the Lion), which rises in the east around midnight and climbs steadily through the night, peaking in the pre-dawn hours",
    peakZHR: "typically 10–20 meteors per hour in non-storm years; historically has exceeded 10,000 per hour during rare storm events tied to Tempel–Tuttle's 33-year return",
  },
  {
    name: "Geminids",
    peakMonth: 12,
    peakDay: 13,
    peakEndMonth: 12,
    peakEndDay: 14,
    description: "Widely considered the best annual meteor shower. High rates, bright meteors, a long activity window, and early-evening visibility make this the most accessible major shower of the year.",
    activityLevel: "High",
    parentComet: "the rocky asteroid 3200 Phaethon, which sheds material as it swings to within 0.14 AU of the Sun — making Geminids the only major annual shower driven by an asteroid rather than a comet",
    radiantConstellation: "Gemini (the Twins), near the bright star Castor — unusually, the radiant rises in the early evening, so Geminids can begin well before midnight unlike most other showers",
    peakZHR: "around 120–150 meteors per hour, the highest typical peak rate of any major annual shower",
  },
];
