/**
 * SW build smoke tests
 *
 * public/sw.js is now generated by `scripts/buildSw.js` (esbuild) from
 * worker/sw.js, which imports parseKpFromTabular and shouldTriggerNotification
 * directly from lib/utils/swShared.js. There is no longer a hand-maintained
 * copy in the service worker — esbuild inlines the same source.
 *
 * These tests verify that the built bundle:
 *   1. Contains the expected functions (build step ran and succeeded).
 *   2. Produces correct results — catching any transformation the bundler
 *      might apply that changes behaviour.
 *
 * For thorough logic tests of the underlying helpers, see:
 *   tests/lib/swKpParsing.test.ts
 *   tests/lib/swNotifications.test.ts
 */

import { readFileSync } from 'fs'
import { resolve } from 'path'
import { describe, it, expect } from 'vitest'

// ── Helpers ───────────────────────────────────────────────────────────────────

const SW_BUNDLE = readFileSync(resolve(__dirname, '../../public/sw.js'), 'utf8')

/**
 * Extract a named function from the built sw.js by brace-matching and return
 * it as a callable. Throws if the function is not found, which is itself a
 * useful signal that the build step did not run or the output changed shape.
 */
function extractSwFn(name: string): (...args: unknown[]) => unknown {
  const pattern = new RegExp(`function ${name}\\([^)]*\\)\\s*\\{`)
  const m = pattern.exec(SW_BUNDLE)
  if (!m) throw new Error(`'${name}' not found in public/sw.js — did the build step run?`)

  let depth = 0
  let i = m.index
  for (; i < SW_BUNDLE.length; i++) {
    if (SW_BUNDLE[i] === '{') depth++
    else if (SW_BUNDLE[i] === '}') { if (--depth === 0) break }
  }
  const funcText = SW_BUNDLE.slice(m.index, i + 1)
  return eval(`(${funcText})`)
}

const swParseKp = extractSwFn('parseKpFromTabular') as (data: unknown) => number | null
const swShouldTrigger = extractSwFn('shouldTriggerNotification') as (
  kp: number | null,
  prefs: { kp: number; prob: number },
  bz: number | null,
  maxProb: number | null
) => boolean

// ── parseKpFromTabular ────────────────────────────────────────────────────────

const VALID_KP_TABLE = [
  ['time_tag', 'Kp', 'status'],
  ['2024-01-15 06:00:00', '3.00', 'official'],
  ['2024-01-15 09:00:00', '5.33', 'official'],
]

describe('parseKpFromTabular — bundled SW behaviour', () => {
  const cases: [string, unknown, number | null][] = [
    ['returns null for undefined',             undefined,                          null],
    ['returns null for null',                  null,                               null],
    ['returns null for empty array',           [],                                 null],
    ['returns null for header-only array',     [['time_tag', 'Kp']],              null],
    ['returns null for non-array header row',  [42, ['2024-01-15', '3.00']],      null],
    ['returns null when Kp column absent',     [['time_tag', 'speed'], ['x','y']], null],
    ['returns null for NaN Kp value',          [['Kp'], ['bad']],                 null],
    ['parses the last row correctly',          VALID_KP_TABLE,                   5.33],
    ['handles "0.00"',                         [['Kp'], ['0.00']],                 0],
    ['handles "9.00"',                         [['Kp'], ['9.00']],                 9],
  ]

  for (const [label, input, expected] of cases) {
    it(label, () => {
      const result = swParseKp(input)
      if (expected === null) {
        expect(result).toBeNull()
      } else {
        expect(result).toBeCloseTo(expected)
      }
    })
  }

  it('returns the Kp of the last row in a realistic multi-row table', () => {
    expect(swParseKp(VALID_KP_TABLE)).toBeCloseTo(5.33)
  })
})

// ── shouldTriggerNotification ─────────────────────────────────────────────────

const PREFS = { kp: 4, prob: 15 }

describe('shouldTriggerNotification — bundled SW behaviour', () => {
  const cases: [string, [number | null, typeof PREFS, number | null, number | null], boolean][] = [
    ['false when kp is null',                   [null,  PREFS, null,  null], false],
    ['false when nothing meets threshold',       [2,     PREFS, -2,   5],   false],
    ['true when kp meets threshold',             [4,     PREFS, null, null], true],
    ['true when kp exceeds threshold',           [7,     PREFS, null, null], true],
    ['true when maxProb meets threshold',        [1,     PREFS, null, 15],   true],
    ['true when maxProb exceeds threshold',      [1,     PREFS, null, 80],   true],
    ['true when bz is exactly -5',               [1,     PREFS, -5,   null], true],
    ['true when bz is strongly negative',        [1,     PREFS, -12,  null], true],
    ['false when bz is -4 (above cutoff)',       [2,     PREFS, -4,   5],   false],
    ['true when all three conditions are met',   [5,     PREFS, -8,   20],   true],
    ['false when kp=0, prob=0, bz=0',           [0,     PREFS, 0,    0],   false],
  ]

  for (const [label, args, expected] of cases) {
    it(label, () => {
      expect(swShouldTrigger(...args)).toBe(expected)
    })
  }
})
