'use strict';
/**
 * buildSw.js — Service worker bundler
 *
 * Bundles worker/sw.js (and its imports from lib/utils/swShared.js) into a
 * single plain-JavaScript file at public/sw.js using esbuild.
 *
 * This replaces the old scripts/inlineSwFunctions.js text-splice approach.
 * With bundling, lib/utils/swShared.js is the single canonical source for the
 * shared helper functions — no separate copy needs to be maintained in sw.js.
 *
 * When it runs: automatically as the first step of `npm run build`.
 * To run manually: node scripts/buildSw.js
 */

const esbuild = require('esbuild');
const path    = require('path');

const ROOT = path.join(__dirname, '..');

esbuild.build({
  entryPoints: [path.join(ROOT, 'worker', 'sw.js')],
  outfile:     path.join(ROOT, 'public', 'sw.js'),
  bundle:      true,
  format:      'iife',   // Single flat file — no module syntax in the output
  platform:    'browser',
  target:      ['chrome91', 'firefox114', 'safari16'],
  // Keep function names readable so the parity tests can still extract them by name
  minify:      false,
  banner: {
    js: '// Generated by scripts/buildSw.js — edit worker/sw.js, not this file.',
  },
}).then(() => {
  process.stdout.write('buildSw: bundled worker/sw.js → public/sw.js\n');
}).catch((err) => {
  process.stderr.write(`buildSw error: ${err.message}\n`);
  process.exit(1);
});
